spring:
  application:
    name: ru.urfu

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/master-changelog.xml
    enabled: true

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 5GB

  app:
    upload:
      dir: ./uploads

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

